### ISSUE TITLE
Running comic generation on a file that's still open by kiwibot results in python exception

### ISSUE THREAD

**Issue by jpirie** [jpirie/Kiwibot#10]
This is a minor bug, as all the output has been produced at that point, but python should handle the exception gracefully and display a warning.

**Comment by jpirie** [comment]
Output from running make that generates the exception is below:

```
Reading history log: 2013-05-12.log Traceback (most recent call last): File "./generate-comics.py", line 45, in <module> fileContents = fileHandler.readlines() File "/usr/lib/python3.3/codecs.py", line 300, in decode (result, consumed) = self._buffer_decode(data, self.errors, final) UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 7410: invalid continuation byte
```
